version: "3"
services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 8888:8888
      - 9527:9527
    volumes:
      - /home/activities/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /home/activities/nginx/html/:/usr/share/nginx/html

  activities-web:
    build:
      context: /home/activities/activities-web
      dockerfile: ./Dockerfile
    ports:
      - "8083:8083"
    restart: always
    depends_on:
      - nginx
    environment:
      IP: "121.196.145.132"
      PORT: "3306"
      DRIVERCLASSNAME: "com.mysql.cj.jdbc.Driver"
      DBNAME: "work"
      URL: "jdbc:mysql://121.196.145.132:3306/activities?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false"
      USERNAME: "root"
      PASSWORD: "123456"
  activities-admin:
      build:
        context: /home/activities/activities-admin
        dockerfile: ./Dockerfile
      ports:
        - "8084:8084"
      restart: always
      depends_on:
        - nginx
      environment:
        IP: "121.196.145.132"
        PORT: "3306"
        DRIVERCLASSNAME: "com.mysql.cj.jdbc.Driver"
        DBNAME: "work"
        URL: "jdbc:mysql://121.196.145.132:3306/activities?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false"
        USERNAME: "root"
        PASSWORD: "123456"